env:
  global:
    - CODECLIMATE_REPO_TOKEN=6c7aa04b7c8ea5bd90845bc6dccbad4d23785e7d263be4e27214d6d0b4f457de

sudo: required

language: python

services:
  - docker

before_install:
  - docker pull shookees/kaldi-gstreamer-server

script:
 - docker run -v `pwd`:/opt/kaldi-gstreamer-server-test shookees/kaldi-gstreamer-server bash -c "cd /opt/kaldi-gstreamer-server-test/ && python3.5 -m unittest discover test/unittests test_*.py"